---
include:
  - project: 'kalvinov/gitlab-templates'
    ref: main
    file: docker.yaml

variables:
  IMG_NAME: gocli

stages:
  - build
  - release

compile:
  image: golang:latest
  stage: build
  script:
    - CGO_ENABLED=0 go build 
  artifacts:
    paths:
      - gocli
  only:
    - tags

build_docker:
  extends:
    - .docker_job
  tags:
    - docker
  stage: release
  script:
    - docker build -t ${AWS_REGISTRY}/${IMG_NAME}:$CI_COMMIT_TAG -f Dockerfile ./
    - docker push ${AWS_REGISTRY}/${IMG_NAME}:$CI_COMMIT_TAG
    - docker tag ${AWS_REGISTRY}/${IMG_NAME}:$CI_COMMIT_TAG registry.gitlab.com/kalvinov/devops/gocli:$CI_COMMIT_TAG
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker push registry.gitlab.com/kalvinov/devops/gocli:$CI_COMMIT_TAG
  only:
    - tags